-- Custom SQL migration file, put your code below! --
-- BM25 indexes disabled: pg_search extension not available on this Supabase project.
-- See 0090_enable_pg_search.sql. Re-enable both migrations when running on
-- paradedb/paradedb:latest-pg17 or a ParadeDB-backed Postgres.
